version: '3.1'

services:
  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_java
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    # volumes:
    #   - ./data1:/var/lib/mysql
    ports:
      - 3308:3308
    expose:
      -  3308
    networks:
      - dev2-network

  docker_from_zero_to_mastery_java:
   image: docker_from_zero_to_mastery_java
   restart: always
   build: ./app
   working_dir: /app
   environment:
     TZ: America/Sao_Paulo
     SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/docker_from_zero_to_mastery_java?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
     SPRING.DATASOURCE.USERNAME: root
     SPRING.DATASOURCE.PASSWORD: docker
   ports:
     - 80:80
   command: mvn spring-boot:run
   depends_on:
     - db
   networks:
     - dev2-network

networks:
  dev2-network:
    driver: bridge