name: Continuos Integration with Github, Github Actions, Docker Hub

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:    
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Java JDK
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven        
    - name: Build Application Jar
      working-directory: ./02-app/app
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./02-app
      run: docker compose build
      
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag docker_from_zero_to_mastery:latest ${{ secrets.DOCKER_USERNAME }}/docker_from_zero_to_mastery:latest
        docker tag docker_from_zero_to_mastery:latest ${{ secrets.DOCKER_USERNAME }}/docker_from_zero_to_mastery:${{ github.run_id }}
       
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery:${{ github.run_id }}
